### ISSUE TITLE
Pull from a different remote branch than the one being tracked

### ISSUE THREAD

**Issue by mhowes82** [oxygenxml/oxygen-git-client-addon#107]
Is it possible to pull from a remote branch into a different branch? For example, I checkout Branch A and want pull changes from Branch B into Branch A. Thanks!

**Comment by sorincarbunaru** [comment]
Hello!

Unfortunately this is not yet possible. We will keep this in mind, but as we already have quite a few things planned to be developed in the near future, I can't predict when the improvement you requested will be done.

**Comment by sorincarbunaru** [comment]
In v5.4.0 of the Git Client it is now possible to pull changes from another remote branch than the one being tracked.
