### ISSUE TITLE
No content in Git History when showing it from Window > Show view

### ISSUE THREAD

**Issue by sorincarbunaru** [oxygenxml/oxygen-git-client-addon#136]
I think this happens the first time you show it...

**Comment by sorincarbunaru** [comment]
When showing the view from Window > Show view, we should also call `com.oxygenxml.git.view.history.HistoryController.showRepositoryHistory()`, I think...

**Comment by AlexSmarandache15** [comment]
This issue has been resolved in 4.0.0 release.
