### ISSUE TITLE
GitLFS Support

### ISSUE THREAD

**Issue by kirkilj** [oxygenxml/oxygen-git-client-addon#155]
I probably mentioned GitLFS in an email a while ago, but I'll list it here in case other customers have similar needs. 

The last time we spoke, it sounded like there wasn't as big a desire for it from the Oxygen user base to put it ahead of all the basic features you've been adding to the plugin over the last couple years, so I don't blame you. If I recall, you noted that the source code is right here on GitHub and that we could implement it if we needed to. JGit appears to have supported it since 2016. I have no idea how transparent JGit makes LFS to the consumer of the JGit API, but I'd think the EGit source code for Eclipse might provide a clue. Btw, the next version of JGit (6.0.0) is due out in a week or so:

> Release Date: Wednesday, December 8, 2021
This release is part of Eclipse IDE 2021-12.

Our specific DocTools group does not recommend using LFS if the only binaries in a repo are small images such as screenshots under 1MB. Studies were done by some heavy Unity developers with lots of binary assets, and they discovered that the network/handshake overhead of lots of small binaries over LFS isn't worth it for small binaries that rarely change. Rich media documentation assets though are prime candidates for organizations who employ LFS servers. Unfortunately, it looks like the only way to specify which files should be stored on an LFS server vs Git through built-in means is to specify filename extensions or to explicitly list every pathname that should be stored in LFS in the .gitattributes file.  Some people run something like a command like the following to identify those files: `find * -type f -size +1M`. Others have tried pre-commit hooks or something similar.

There was talk years ago on the Git project to add a size criteria in addition to the file extension, but I don't think it went anywhere. I could be wrong. A custom smudge filter can be created to apply a combination of extension and size criteria. The full thread is at https://github.com/git-lfs/git-lfs/issues/282.

One of our main Git servers, Gerrit from Google, uses JGit as well and utilizes the LFS server-side functionality. Oxygen would obviously only need the client libraries.

**Comment by kirkilj** [comment]
It looks like JGit has had some level of LFS support for quite a while now, with some enhancements added in the most recent release https://projects.eclipse.org/projects/technology.jgit/releases/6.1.0/review.

**Comment by chrispy-snps** [comment]
@kirkilj - thanks for noting this! LFS is something I've been meaning to check out (no pun intended).

**Comment by kirkilj** [comment]
Can anyone from Syncrosoft speak to the priority of this request amongst the others you're considering?

Some of our documentation repos are tightly integrated with the R&D software repos, so the GitLFS requirement is a deal-breaker for those projects and would need to use other Git tools for that purpose.

**Comment by sorincarbunaru** [comment]
For futher references: internal issue ID is EXM-43578.

**Comment by AlexJitianu** [comment]
We released version 5.2.0 in which we will recognize and work with LFS repositories. We don't have a built-in way for defining LFS related things in the repository, but if the repository is properly configured, LFS will be recognized and files will be treated accordingly.

**Comment by chrispy-snps** [comment]
The 5.2.0 add-on update is a big step forward - thank you @AlexJitianu!

**Comment by kirkilj** [comment]
Great news! This was worth breaking my abstinence from work emails while on vacation. I'll have to contain myself for another 12 days.

**Comment by AlexJitianu** [comment]
Enjoy your vacation, John! One thing I've forgot to mention. If you are behind a proxy this environment variable needs to be set: 
`set HTTPS_PROXY=http://my.proxy.com:5000`
