### ISSUE TITLE
Show current branch in Git Staging view

### ISSUE THREAD

**Issue by xephon2** [oxygenxml/oxygen-git-client-addon#159]
It would be helpful to see the current branch in the `Git Staging` view also.

![image](https://user-images.githubusercontent.com/3266567/148065184-4043796a-8ce9-4b39-9d61-1d66ec224233.png)

**Comment by AlexJitianu** [comment]
Hi Stefan,
For the next release we intend to put back the branch select widget 👍 
![image](https://user-images.githubusercontent.com/7802649/148072150-b4e70b26-e1a2-498d-bf43-628716a45373.png)

**Comment by chrispy-snps** [comment]
@AlexJitianu - thank you for implementing this in the 4.0.0 release - my group is very appreciative! This is very helpful to ensure that commits go where they belong.

**Comment by xephon2** [comment]
Thanks a lot. :pray:
