### ISSUE TITLE
Refresh on view: Git History and Git Branch Manager

### ISSUE THREAD

**Issue by xephon2** [oxygenxml/oxygen-git-client-addon#160]
When opening the Git History or Git Branch Manager views they are empty. I have to manually click the refresh button. Would it be possible that you trigger a refresh with an "on view" event?

![image](https://user-images.githubusercontent.com/3266567/148508932-3715e33c-a63e-4bbc-b5e4-46576de13f45.png)

**Comment by chrispy-snps** [comment]
@xephon2 - does the 4.0.0 release fix this for you?

**Comment by AlexSmarandache15** [comment]
This issue has been resolved in 4.0.0 release.
