### ISSUE TITLE
In Windows, Oxygen UI temporarily freezes after changing focus to Oxygen with Git Staging view shown

### ISSUE THREAD

**Issue by chrispy-snps** [oxygenxml/oxygen-git-client-addon#163]
I am using the v4.0.0 release of the Git plugin in Windows 10.

I noticed that if I change focus from another application to Oxygen (via Alt-Tab or by window activation) and the Git Staging view is shown, then the Oxygen UI becomes unresponsive for several seconds. This is repeatable and happens every time the focus changes into Oxygen. If the Git Staging view is not shown, then the behavior does not occur.

![git_plugin_oxygen_ui_hangs](https://user-images.githubusercontent.com/50950969/154097676-166cc445-931c-47e0-b90a-82f9f0320bd9.gif)

**Comment by chrispy-snps** [comment]
@AlexSmarandache15 - do you have a development build with the fix that I could test?

**Comment by AlexSmarandache15** [comment]
Hi, @chrispy-snps! We have just released version 4.0.1 which solves this issue.
