### ISSUE TITLE
4.0.0 problem

### ISSUE THREAD

**Issue by wujastyk** [oxygenxml/oxygen-git-client-addon#164]
XML Author 24.0, build 2022012607, on Linux Mint:

After installation of the new update, and restarting oXygen, I get this during startup:

![Screenshot from 2022-02-16 15-59-56](https://user-images.githubusercontent.com/762246/154372188-eb3f1275-bb8d-4e79-a6a7-cbf69d8ae74b.png)

Then, the Git sidebar for committing has no content (no windows or menus)

**Comment by AlexJitianu** [comment]
Hello,

I'm sorry for the inconvenience. We need to enable logging to understand what's happening. Please unzip the attached archive inside {oxygenInstallDir}/lib without creating any additional folders. Afterwards, edit {oxygenInstallDir}/lib/libraries.list and append `;log4j-slf4j-impl-2.14.1.jar`  . Start Oxygen and reproduce the error. If it doesn't appear, you might need to go to _Windows->Show view_ and select the _Git Staging_ view.
[enable-logging-files.zip](https://github.com/oxygenxml/oxygen-git-client-addon/files/8086906/enable-logging-files.zip)

**Comment by wujastyk** [comment]
I'm sorry, I didn't know about the log files (and don't know where to find them).  After the initial error with 4.0.0, I reinstalled version 3.0.1, then 4 again following your git post, then 3 again so that I can work.  At this point, I'm afraid I'm under work pressure and I need to get on with work and I can't give more time to reinstalling 4 and debugging.  My apologies.

**Comment by AlexJitianu** [comment]
If you do see a folder named _oxygenLog_ folder on your Desktop, please zip it and send it to support@oxygenxml.com. We will try to reproduce it ourselves in the meantime.

**Comment by AlexSmarandache15** [comment]
This issue has been resolved in release 4.0.1. Let us know if somehow it still persists.

**Comment by wujastyk** [comment]
Thank you!
