### ISSUE TITLE
Release 5.0.0

### ISSUE THREAD

**Issue by AlexJitianu** [oxygenxml/oxygen-git-client-addon#168]
- [x] Make sure the automated tests pass. Check Jenkins (https://jenkins-master.sync.ro/job/oxygen-git-plugin/).
- [x] Add the "What's New" list to **addon.xml**. A JIRA Search can be used to obtain a list with all the issues resolved since the last release.
- [x] When ready for release, start a Jenkins build providing the release version and selecting the RELEASE check box.
- [x] Add a new release in the GitHub Releases section and and put in it the addon archive and the "What's New" list. See https://github.com/oxygenxml/oxygen-git-plugin/releases.
- [x] Check the new version is available on the default update site.
- [x] Send e-mail to the users who agreed to be notified when what they requested has been implemented.
- [x] Update the forum threads where users requested things that have been implemented for the current release.
- [x] Promote the release on social media, oxygen-users list and DITA list.
- [x] Update internal version on Jenkins.

**Comment by wujastyk** [comment]
oXygen version:
![image](https://user-images.githubusercontent.com/762246/195394508-6d451e9d-cc01-4e7e-a9aa-ee350054fcd2.png)


My installation shows this Git client plugin update as being "incompatible".
![image](https://user-images.githubusercontent.com/762246/195394404-8d4166ca-eb37-4fb0-b262-b02d42aac558.png)

**Comment by AlexJitianu** [comment]
@wujastyk , somehow I've missed your message, I'm sorry! Unfortunately, the new features from version 5.0.0 required the use of a new API which was introduced in Oxygen 25 and because of that we were forced to increase its compatibility version.

**Comment by wujastyk** [comment]
No problem. I and my group have upgraded to 25.  Thanks!
