### ISSUE TITLE
In history view, provide a bit more name for longer origin HEAD markers

### ISSUE THREAD

**Issue by chrispy-snps** [oxygenxml/oxygen-git-client-addon#169]
In the Git History view, maybe the origin HEAD markers could be a bit wider, since the origin prefix will always add a bit more width:

![git_addon_history](https://user-images.githubusercontent.com/50950969/195855256-2e75ffb1-239b-4ad0-aa0f-2af855b7cc2c.PNG)

In the image above, I needed to revert my current local commit in the red branch. I accidentally reset my HEAD to the commit just below it, in the green branch, which caused a diverged local branch state with dozens of desynchronized commits on both sides! I panicked quite a bit before I figured out what I did. And if I did that (and I'm our local Git "expert"), I can't imagine how a writer would react!

**Comment by AlexJitianu** [comment]
Hi,

We have 3 possibilities to help the user in this situation:
1. Present the entire label if there's enough space
2. We can have a mode in which we shorten the terms: {{origin/release/U-2022.12}} becomes {{o/r/U-2022.12}}. We could activate it automatically when there isn't enough space, although I'm not sure if the user will understand what happened. 
3. We can tokenize the label in _remote_,_path_, _name_ and use different colors for each to help the user identify a label.

**Comment by chrispy-snps** [comment]
@AlexJitianu - Thank you for giving this some thought!

Because 2 and 3 can be built on top of 1, I like the idea of implementing 1, then seeing what further feedback is obtained after that change is released. If the change is acceptable to everyone, then there is no need to implement further complexity.

I recognize that the plugin is used in a variety of display conditions. Some people use Oxygen on a 32" widescreen monitor at high resolutions, while others use it on economical laptops with medium-resolution screens and Windows desktop scaling set to 150%!

**Comment by AlexJitianu** [comment]
In the 5.1.0 version released last week we implemented 1. I will close this for now and we will get back to it and implement 2. or 3. if the need arises in the future.

**Comment by chrispy-snps** [comment]
@AlexJitianu - the enhancement works great. Thank you!
