### ISSUE TITLE
In the Stashes dialog, use a movable divider between the stash names and file list

### ISSUE THREAD

**Issue by chrispy-snps** [oxygenxml/oxygen-git-client-addon#170]
In the **Stashes** dialog, currently the width allocation for the stash names and file list appears to be fixed:

![image](https://user-images.githubusercontent.com/50950969/197871709-8b1bf6e4-7dd5-4ad0-bc82-6aa7463f2d82.png)

It would be nice if the divider at the red line could become draggable, so that more room can be allocated to file names.

**Comment by AlexJitianu** [comment]
Yes, it is something helpful that can be done quickly and would help. Meanwhile, in case you didn't notice it yet, there is a tooltip that can help identify the correct file.

**Comment by AlexJitianu** [comment]
We added a movable divider in the 5.1.0 release

**Comment by chrispy-snps** [comment]
@AlexJitianu - the enhancement works great. Thank you!
