### ISSUE TITLE
Provide Listener interface for branch switches

### ISSUE THREAD

**Issue by kirkilj** [oxygenxml/oxygen-git-client-addon#174]
Our custom plugin would like to make sure our custom menus and other UI elements are properly enabled or disabled when a writer switches a branch, which may different properties and metadata that the enablement depends upon. 

We do have a Project change listener implementer that updates the internal state of our plugin, but if the user is in the same project but switches branches, we may not get the same opportunity.

Radu mentioned in an email that there's no current mechanism for cross-plugin communication like that. Is there a way that the OxygenSDK could provide way for the Git client plugin to communicate to it that a branch has changed so our plugin could listen for that event and respond?

Radu also mentioned that a branch change might trigger a project change, even if the project file name is the same in both branches as well as the contents.

I suppose we could poll the value of the Git client's ${git(short_branch_name)} editor variable as a work around, so if you have a recommendation about the ideal way to implement this, I'm all ears.

Thanks.

**Comment by AlexJitianu** [comment]
Hi John,
Even if we publish such an API in the Git Client, currently plugins are isolated from one another so your plugin has no mechanism to use this API. We would have to first implement this cross-plugin communication within Oxygen. 

Yes, you can poll _${git(short_branch_name)}_ to detect the change. If your plugin contributes a view, perhaps you can make these checks on a focus gain event.

**Comment by kirkilj** [comment]
Thanks for the quick response.

(1) This may be a kludge, but I'd like to know in concept if you think it could also work to have a project-specific custom editor variable that includes ${git(short_name)} as it's value. Would this be evaluated always if the branch changes?

(2) Do you think there would be other business drivers for Syncrosoft to consider adding a delegation proxy or broker in Oxygen core that could safely relay requests to another plugin via introspection or other such magic? For security's sake, this might involve asking the user if they want to allow plugin X to have certain privs on plugin Y, perhaps with the option to only allow it for digitally signed plugins.

I know this second one is not trivial by any means, but perhaps if you keep it in the back of your mind and discuss with your peers, it might form the basis for extending the Oxygen ecosystem or at lease allow custom plugin developers to leverage your many plugins in new ways.

Best regards,

John

**Comment by AlexJitianu** [comment]
Hi John,
Somehow I've missed your reply, sorry for that. 
(1) Yes, there is no caching involved, so it should work.
(2) We don't have such a huge plugin community to justify it. If both plugins are developed by you, you can pass information between them through the `PluginWorkspace.getOptionsStorage()` API. One plugin writes options, the other listens on them.

**Comment by AlexJitianu** [comment]
What we could do fairly easy is to write a couple of options, like GIT_REPOSITORY or GIT_CHECKOUT_BRANCH. Your plugin could add listeners on these options and react immediately when once the user changes the repository or the branch. Are there other events you are interested in?

**Comment by kirkilj** [comment]
I'm a bit fried at the moment to consider other possible events, but for our current purposes, we just need a way to refresh our plugin's internal state when a branch change occurs while the user has the same project open. The events you mentioned would be perfect for this. Thanks.

**Comment by AlexJitianu** [comment]
We released version 5.2.0 in which we save these two options:

    PLUGIN_CUSTOM_OPTIONS.com.oxygenxml.git.current.branch
    PLUGIN_CUSTOM_OPTIONS.com.oxygenxml.git.selected.repository

This means that you can add a listener on _ro.sync.exml.workspace.api.options.WSOptionsStorage_ from another plugin and you will be notified when they are changed.

**Comment by kirkilj** [comment]
Wow. Thanks so much for providing a way to do this.
