### ISSUE TITLE
Minor UX suggestion: Add a "badge" to push toolbar icon when no upstream is defined yet

### ISSUE THREAD

**Issue by kirkilj** [oxygenxml/oxygen-git-client-addon#92]
Thanks for adding the ability to push to an upstream branch if it doesn't exist by providing the hover hint on the "push" button that informs the user that a remote branch will be pushed to the server with the same name. However, the user won't necessarily know at a glance that there's something committed that hasn't been pushed to an upstream branch if there's no number badge indicating that there are commits pending. 

For the use case where someone is working only on a local branch, temporarily or not, I can see the logic of not showing an indicator that's been used thus far to show how far ahead the local repo is from its remote. Perhaps the interpretation of the number could change to indicate the number of commits that would be pushed to an upstream branch, should the user decide to do so. Perhaps it might also be useful to add a visual annotation to the number of commits so it indicates at a glance whether the local branch is with or without an upstream branch.

I'm sure there could be many other options, such as making the "push' button into a pull-down with other options, as is done for "pull" if you have had other requests for options to the push command. There are a ton of options, so you'd have to pick wisely to narrow it down to a few options if you went in that direction.

Thoughts?

**Comment by AlexJitianu** [comment]
Hi John,

I can see the benefit of having a visual indicator that the branch has evolved beyond it's creation point. There isn't a lot of space on the toolbar, so finding a way to decorate it in a meaningful, intuitive way could be a challenge... I will raise this during the following meeting to see what suggestions come up.

**Comment by sorincarbunaru** [comment]
@kirkilj, I guess you and your users have noticed the + sign that decorates the Push button when there is no upstream branch. Is this sufficient for now? :)

**Comment by sorincarbunaru** [comment]
This has been implemented several months ago and the improvements is already available.
